FROM python:3.11-slim

WORKDIR /app

# Copy all Python files and requirements.txt into the container
COPY requirements.txt ./
COPY ./ .
COPY .env .env

# Install dependencies from requirements.txt and supervisord
# RUN pip install --verbose --no-cache-dir -r requirements.txt supervisor
RUN pip install --no-cache-dir -r requirements.txt

# # Expose ports for each backend service
EXPOSE 5000

# Command to run supervisord
CMD ["python", "app.py"]